# Generated by Django 5.1.2 on 2024-11-22 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date de naissance de l'utilisateur (YYYY-MM-DD)"),
            preserve_default=False,
        ),
    ]
