# Generated by Django 5.1.2 on 2024-11-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_issue_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(help_text='Corps du commentaire.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Responsable', 'Responsable'), ('Contributeur', 'Contributeur')], help_text='Permissions du contributeur.', max_length=12),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(help_text='Rôle du contributeur.', max_length=12),
        ),
    ]
