# Generated by Django 5.1.2 on 2024-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_comment_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Auteur', 'Auteur'), ('Contributeur', 'Contributeur')], help_text='Rôle du contributeur.', max_length=12),
        ),
    ]
