# Generated by Django 5.1.2 on 2024-12-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_desc_issue_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
    ]
