# Generated by Django 5.1.2 on 2024-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_contributor_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
